import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import AppProvider from "@/layout/app-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/auth-options";
import MainLayout from "@/layout/main-layout";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopping System",
  description: "Generated by Exclusive shopping system",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(roboto.variable, "h-full antialiased font-roboto")}
    >
      <body
        className="min-h-full flex flex-col">
        <AppProvider session={session}>
          <MainLayout>
            {children}
          </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
